#ifndef DRIVER_HYGRO_REGS_H
#define DRIVER_HYGRO_REGS_H

#include "lib/utils.h"

#define HYGRO_REPEATABILITY_HIGH_TMS 15
#define HYGRO_REPEATABILITY_MEDIUM_TMS 6
#define HYGRO_REPEATABILITY_LOW_TMS 4

// Periodic measurement start commands
#define HYGRO_START_MEAS_HRS_MSB 0x24
#define HYGRO_START_MEAS_HRS_LSB 0x00 // High repeatability
#define HYGRO_START_MEAS_MRS_MSB 0x24
#define HYGRO_START_MEAS_MRS_LSB 0x0B // Medium repeatability
#define HYGRO_START_MEAS_LRS_MSB 0x24
#define HYGRO_START_MEAS_LRS_LSB 0x16 // Low repeatability

#define HYGRO_START_MEAS_HRP_0_5_MSB 0x20
#define HYGRO_START_MEAS_HRP_0_5_LSB 0x32
#define HYGRO_START_MEAS_MRP_0_5_MSB 0x20
#define HYGRO_START_MEAS_MRP_0_5_LSB 0x24
#define HYGRO_START_MEAS_LRP_0_5_MSB 0x20
#define HYGRO_START_MEAS_LRP_0_5_LSB 0x2F

#define HYGRO_START_MEAS_HRP_1_MSB 0x21
#define HYGRO_START_MEAS_HRP_1_LSB 0x30
#define HYGRO_START_MEAS_MRP_1_MSB 0x21
#define HYGRO_START_MEAS_MRP_1_LSB 0x26
#define HYGRO_START_MEAS_LRP_1_MSB 0x21
#define HYGRO_START_MEAS_LRP_1_LSB 0x2D

#define HYGRO_START_MEAS_HRP_2_MSB 0x22
#define HYGRO_START_MEAS_HRP_2_LSB 0x36
#define HYGRO_START_MEAS_MRP_2_MSB 0x22
#define HYGRO_START_MEAS_MRP_2_LSB 0x20
#define HYGRO_START_MEAS_LRP_2_MSB 0x22
#define HYGRO_START_MEAS_LRP_2_LSB 0x2B

#define HYGRO_START_MEAS_HRP_4_MSB 0x23
#define HYGRO_START_MEAS_HRP_4_LSB 0x34
#define HYGRO_START_MEAS_MRP_4_MSB 0x23
#define HYGRO_START_MEAS_MRP_4_LSB 0x22
#define HYGRO_START_MEAS_LRP_4_MSB 0x23
#define HYGRO_START_MEAS_LRP_4_LSB 0x29

#define HYGRO_START_MEAS_HRP_10_MSB 0x27
#define HYGRO_START_MEAS_HRP_10_LSB 0x37
#define HYGRO_START_MEAS_MRP_10_MSB 0x27
#define HYGRO_START_MEAS_MRP_10_LSB 0x21
#define HYGRO_START_MEAS_LRP_10_MSB 0x27
#define HYGRO_START_MEAS_LRP_10_LSB 0x2A

#define HYGRO_FETCH_PERIODIC_DATA_MSB 0xE0
#define HYGRO_FETCH_PERIODIC_DATA_LSB 0x00

#define HYGRO_BREAK_MSB 0x30
#define HYGRO_BREAK_LSB 0x93

#define HYGRO_SOFT_RESET_MSB 0x30
#define HYGRO_SOFT_RESET_LSB 0xA2

#define HYGRO_HEATER_ENABLE_MSB 0x30
#define HYGRO_HEATER_ENABLE_LSB 0x6D
#define HYGRO_HEATER_DISABLE_MSB 0x30
#define HYGRO_HEATER_DISABLE_LSB 0x66

#define HYGRO_READ_ST_REG_MSB 0xF3
#define HYGRO_READ_ST_REG_LSB 0x2D

#define HYGRO_CLEAR_ST_REG_MSB 0x30
#define HYGRO_CLEAR_ST_REG_LSB 0x41

// Status register bits
#define HYGRO_ST_DATA_CHECKSUM BIT(0)
#define HYGRO_ST_CMD BIT(1)
#define HYGRO_ST_SYS_RESET BIT(4)
#define HYGRO_ST_T_TRACK_ALERT BIT(10)
#define HYGRO_ST_RH_TRACK_ALERT BIT(11)
#define HYGRO_ST_HEATER BIT(13)
#define HYGRO_ST_PENDING_ALERTS BIT(15)

#endif
