#ifndef DRIVER_DISPLAY_CMDS_H
#define DRIVER_DISPLAY_CMDS_H

#include "display.h"
#include <stdint.h>

#define DISPLAY_PAGE_COUNT DISPLAY_SCREEN_H / 8
#define DISPLAY_CMD_RING_SZ 100
#define DISPLAY_FB_SZ 1024
#define DISPLAY_MAX_FB_CMDS_SZ 32
#define DISPLAY_CMD_BUF_MAX_SZ 16

typedef enum
{
    DISPLAY_CTRL_CMD_ONLY = 0x00,
    DISPLAY_CTRL_DATA_ONLY = 0x40,
    DISPLAY_CTRL_CMD = 0x80,
    DISPLAY_CTRL_DATA = 0xC0
} display_ctrl_t;

typedef enum
{
    DISPLAY_CMD_SET_CONTRAST = 0x81,
    DISPLAY_CMD_DISPLAY_GDDRAM = 0xA4,
    DISPLAY_CMD_ENTIRE_DISPLAY_ON = 0xA5,
    DISPLAY_CMD_NORMAL_DISPLAY = 0xA6,
    DISPLAY_CMD_INVERSE_DISPLAY = 0xA7,
    DISPLAY_CMD_DISPLAY_OFF = 0xAE,
    DISPLAY_CMD_DISPLAY_ON = 0xAF,

    DISPLAY_CMD_HRSCROLL = 0x26, // 0x00, PG_START, SCROLL_STEP, PG_END, 0xFF
    DISPLAY_CMD_HLSCROLL = 0x27, // ...
    DISPLAY_CMD_DEACTIVATE_SCROOL = 0x2E,
    DISPLAY_CMD_ACTIVATE_SCROOL = 0x2F,

    DISPLAY_CMD_ADDR_MODE = 0x20,    // 0x00 for horizontal
    DISPLAY_CMD_SET_COL_ADDR = 0x21, // start, end
    DISPLAY_CMD_SET_PG_ADDR = 0x22,  // start, end

    DISPLAY_CMD_CHARGE_PUMP = 0x8D,
    DISPLAY_CMD_DIS_PUMP = 0x10,
    DISPLAY_CMD_EN_PUMP = 0x14,

    DISPLAY_CMD_CLOCK_DIVIDE = 0xD5,
    DISPLAY_CMD_START_LINE = 0x40,
    DISPLAY_CMD_SEG_REMAP_START_0 = 0xA0,
    DISPLAY_CMD_SEG_REMAP_START_127 = 0xA1,
    DISPLAY_CMD_SET_MUX_RATIO = 0xA8,
    DISPLAY_CMD_SCAN_DIR_NORMAL = 0xC0,
    DISPLAY_CMD_SCAN_DIR_REMAPPED = 0xC8,
    DISPLAY_CMD_SET_OFFSET = 0xD3,
    DISPLAY_CMD_SET_COM_PINS = 0xDA,
    DISPLAY_CMD_SET_PRECHARGE_PERIOD = 0xD9,
    DISPLAY_CMD_SET_COMH_DESELECT = 0xDB
} display_cmd_t;

typedef struct
{
    uint8_t buf[DISPLAY_MAX_FB_CMDS_SZ + DISPLAY_FB_SZ];
    uint8_t cmd_len;
    uint8_t num_pages;
} display_fb_t;

typedef struct
{
    uint8_t buf[DISPLAY_CMD_BUF_MAX_SZ];
    uint32_t len;
} display_cmd_buf_t;

#endif
